# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 724936051c5cdff3eb63f2b2c714e36bbb903264933ae7d8c4eb2e2f362585c94672e54bf3902226c3bd6a37a943608960ba5fa137ae58d342f1a4867d18f730

test:
  secret_key_base: cd7b56cf95fd2d7ec8cfb9c9be3c48b906e4170a1e56d5735258e516c6c35a01abfa6cdbf5b7324a65a66360053f00b347255cd94deb0638b216ac9e854a186a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
  

